### PR TITLE
Use random matrices for genric Procrustes tests

### PR DESCRIPTION
**Pull request by FarnazH**
Update Generic Procrustes tests.

### CODE REVIEW

**Comment by FarnazH** [comment]
@fwmeng88 There is one failure ` py38: commands failed`. Can you track it down? Thanks.

**Comment by FarnazH** [comment]
@fwmeng88 do you know what was the problem? I rather use the latest version of `numpy`.

**Comment by fwmeng88** [comment]
I am going to merge this PR and I will keep tracking the issue of potential testing failures. Thanks for making the test nicer and efficient.

@FarnazH

**Review by fwmeng88 — APPROVED** [review]
Looks good to me for now.

**Comment by fwmeng88** [comment]
This may because the use of  `np.pinv` function, you can find more details by search _numpy_ as a keyword on this webpage, https://pipelines.actions.githubusercontent.com/L88TwvYONnHmyRbI6FalHuHLAti4UjxJDpUQhMCaWuC7GqR6Ju/_apis/pipelines/1/runs/109/signedlogcontent/7?urlExpires=2021-03-06T01%3A39%3A20.5638687Z&urlSigningMethod=HMACV1&urlSignature=n1%2F1qgE6TeFTveHabRdl0JneMYxVl%2F1UDkU6FU1wJPw%3D

But this is the current understanding of the problem and I will update any findings later.

**Comment by PaulWAyers** [comment]
@fwmeng88 the link you gave didn't work for me.

I would think that np.pinv would be robust, as it is based on SVD, though they use the iterative SVD which is faster but not as robust as the SVD via factorization. We've had problems with that algorithm before (in GOpt), but I'm not sure if that's the issue here. It could be that the rcond parameter needs to be set, but I'm not sure what the error is or for what types of matrices (or all matrices?) it arises.

**Comment by fwmeng88** [comment]
The website links to this failed test, https://github.com/theochem/procrustes/runs/2044066825?check_suite_focus=true. If you click the wheel button on the top right corner, you will find the link to the raw testing log. The test passed on my local machine with the same Python version. 

My only guess is it can be a problem of `numpy.pinv`.  Farnaz proposed to use `scipy.linalg.pinv` to fix the problem of SVD convergence in #69. The trick also works here after my testing both locally and on Github Actions. So, we don't need to set a random seed for the [generic Procrustes](https://github.com/theochem/procrustes/blob/master/procrustes/generic.py).

I will create a PR to fix the problem shortly.
Thanks for the great idea! @FarnazH 
Thanks for the elaborations. @PaulWAyers

**Pull request merged**
