### PR TITLE
Fix positional arguments for `kopt_heuristic_single`

### PR DESCRIPTION
**Pull request by wilhadams**
The positions for the arguments of `kopt_heuristic_single` were changed in f8b6cb5d14f4e8e1ef989f72fa228b9ad02ddbcb but not when they're called in `permutation_2sided`. This commit changes all arguments into keyword arguments.

### CODE REVIEW

**Comment by FarnazH** [comment]
@fwmeng88 can you please see what is the problem with `tox` to help @wilhadams pass his PR through Travis? Thanks.

**Review by fwmeng88 — APPROVED** [review]
The codes are clean and good. I tried to reproduce the error from Travis CI, but everything passed the test in my local machine with `tox` with Python=3.6 and Python=3.8.

I believe this a problem of Travis CI or `.travis.yaml`. So it's safe to merge this PR and I will fix the problem later.

Thanks for the nice contribution! @wilhadams

**Comment by fwmeng88** [comment]
Update: I have fixed the Travis CI checking problem in PR #34. So we are in a good position to merge this PR.

**Review by FarnazH — APPROVED** [review]

**Comment by FarnazH** [comment]
@fwmeng88 can you please fix this merge conflict? I merged your PR first, and then we are getting a conflict here. Thanks.

**Comment by fwmeng88** [comment]
> @fwmeng88 can you please fix this merge conflict? I merged your PR first, and then we are getting a conflict here. Thanks.

I have addressed the conflicting problem in another PR, #38, because I don't have to write access to the original repo. I guess we can close this PR now.

**Comment by FarnazH** [comment]
We should have had enough tests to capture this problem (i.e., the change in the arguments of `kopt_heuristic_single` was not corrected for when the function was called)! Thanks, @wilhadams for catching the bug.

**Comment by FarnazH** [comment]
I fixed the merge conflicts manually (on the command-line) and pushed to `origin/master`, so I think this PR can be closed (again).

**Pull request closed without merging**
